import XCTest
@testable import SigmaMusicKit

/// The parsers against what the Java original makes of the same text (`LyricsParserVectors`, generated by
/// running `LyricsParser.java`): every difference is a song the original reads and this port would not.
final class LyricsParserParityTests: XCTestCase {
    func testMatchesTheJavaOriginal() {
        var failures: [String] = []
        for vector in LyricsParserVectors.cases {
            let lyrics: Lyrics
            switch vector.kind {
            case "lrc": lyrics = LyricsParser.lrc(vector.input)
            case "yrc": lyrics = LyricsParser.yrc(vector.input)
            default: lyrics = LyricsParser.qrc(vector.input)
            }
            let actual = Self.dump(lyrics)
            if actual != vector.expected {
                failures.append("\(vector.kind)/\(vector.name)\n  java:  \(vector.expected.replacingOccurrences(of: "\n", with: " ⏎ "))\n  swift: \(actual.replacingOccurrences(of: "\n", with: " ⏎ "))")
            }
        }
        XCTAssertTrue(failures.isEmpty, "\(failures.count) of \(LyricsParserVectors.cases.count) differ:\n" + failures.joined(separator: "\n"))
    }

    func testTrimIsJavas() {
        XCTAssertEqual(LyricsParser.trim("\u{1}\u{20} a b \u{0D}\u{0A}"), "a b")
        XCTAssertEqual(LyricsParser.trim("\u{3000}x\u{A0}"), "\u{3000}x\u{A0}")
        XCTAssertEqual(LyricsParser.trim(" \t "), "")
    }

    /// The same text as `Gen.dump` in the generator: kind, then one row per line.
    static func dump(_ lyrics: Lyrics) -> String {
        let kind: String
        switch lyrics.kind {
        case .none: kind = "NONE"
        case .instrumental: kind = "INSTRUMENTAL"
        case .line: kind = "LINE"
        case .word: kind = "WORD"
        }
        var out = kind
        for line in lyrics.lines {
            out += "\n\(line.startMs)|\(line.endMs)|\(escape(line.text))|"
            for word in line.words {
                out += "\(word.startMs),\(word.durationMs),\(escape(word.text));"
            }
        }
        return out
    }

    private static func escape(_ text: String) -> String {
        var out = ""
        for unit in text.utf16 {
            switch unit {
            case 0x5C: out += "\\\\"
            case 0x7C: out += "\\p"
            case 0x3B: out += "\\s"
            case 0x2C: out += "\\c"
            case ..<0x20, 0x7F...:
                let hex = String(unit, radix: 16, uppercase: true)
                out += "\\u" + String(repeating: "0", count: 4 - hex.count) + hex
            default: out.unicodeScalars.append(Unicode.Scalar(UInt8(unit)))
            }
        }
        return out
    }
}
